# Generated by Django 3.0.5 on 2020-04-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200411_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
