# Generated by Django 3.0.5 on 2020-04-12 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.TextField(blank=True, max_length=50)),
                ('current_address', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=30)),
                ('aadhar_card_number', models.CharField(blank=True, max_length=30)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
