# Generated by Django 3.0.5 on 2020-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_signupform'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupform',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='signupform',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
